// @ts-nocheck
/**
 * Removes `android.permission.SYSTEM_ALERT_WINDOW` (the "draw over other apps"
 * overlay permission) from RELEASE builds only.
 *
 * RG-040 release-readiness/AUD-REL-002, owner ruling D-09 (Phase 38.4). The Expo
 * bare template declares SYSTEM_ALERT_WINDOW in the app's main manifest as an
 * "optional permission" it ships by default. Orbit never draws overlays, so a
 * release build carrying it is an unnecessary tapjacking/overlay capability
 * (T-38.4-13-01). Debug / dev-client builds still need it: React Native's dev
 * overlays (red box, Perf Monitor) are what the template's `src/debug` manifest
 * copy and React Native's own debug-LIBRARY manifest copy exist for.
 *
 * Manifest-merger priority (developer.android.com/build/manage-manifests):
 * build-type manifest (`src/debug`, `src/release`) > main > library manifests,
 * and merge markers are read from the HIGHER-priority file. That dictates the
 * two mods below:
 *
 *   1. `withAndroidManifest` — a plain DELETION of the permission from the main
 *      manifest, NOT a remove marker there: a main-manifest marker outranks
 *      every library manifest, so it would also strip React Native's
 *      debug-library copy from debug builds. That is exactly why
 *      `android.blockedPermissions` (which writes a main-manifest remove marker,
 *      @expo/config-plugins build/android/Permissions.js) is NOT used here.
 *      Debug still receives the permission from the template `src/debug` copy
 *      and React Native's debug-library copy.
 *   2. `withDangerousMod` — writes `android/app/src/release/AndroidManifest.xml`
 *      holding a single remove marker for the permission. A build-type manifest
 *      outranks main and every library, so the marker applies to release ONLY,
 *      as defense in depth against any library re-adding the permission.
 *
 * Scope is exactly ONE permission (D-09). No other permission is added, removed
 * or modified here — READ_CONTACTS (ADR-003) and the rest stay as they are.
 * This is authored config: generated manifests are never hand-edited.
 */
const fs = require("node:fs");
const path = require("node:path");
const {
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");

const OVERLAY_PERMISSION = "android.permission.SYSTEM_ALERT_WINDOW";

// Build-type manifest for the release variant, relative to the project root.
const RELEASE_MANIFEST_PATH = "android/app/src/release/AndroidManifest.xml";

const RELEASE_MANIFEST_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withReleaseOnlyOverlayPermissionRemoval.js (RG-040, D-09). Do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
  <uses-permission android:name="${OVERLAY_PERMISSION}" tools:node="remove"/>
</manifest>
`;

/** (1) Plain deletion of the overlay permission from the main manifest. */
function withoutMainOverlayPermission(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    if (Array.isArray(manifest["uses-permission"])) {
      manifest["uses-permission"] = manifest["uses-permission"].filter(
        (permission) => permission.$?.["android:name"] !== OVERLAY_PERMISSION,
      );
    }
    return cfg;
  });
}

/** (2) Release build-type manifest carrying the remove marker. */
function withReleaseRemoveMarker(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const target = path.join(
        cfg.modRequest.projectRoot,
        RELEASE_MANIFEST_PATH,
      );
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, RELEASE_MANIFEST_XML);
      return cfg;
    },
  ]);
}

module.exports = (config) =>
  withReleaseRemoveMarker(withoutMainOverlayPermission(config));
