/**
 * gen:models — build-time seed generator for the LiteLLM-sourced model catalog
 * (14-10). Runs on THIS dev box (network only; NOT the desktop/APK build).
 *
 * It fetches LiteLLM's published `model_prices_and_context_window.json`, applies
 * the SAME `filterLiteLLMCatalog` rules the device refresh uses, and writes a
 * bundled seed module (`src/ai/model-registry.seed.generated.ts`). The seed is the
 * OFFLINE / first-run fallback so the picker works out of the box before any user
 * refresh; the on-device runtime cache takes precedence once the user taps Refresh.
 *
 * Run:  npm run gen:models   (commit the regenerated seed)
 *
 * This is dev tooling — it is deliberately outside `src/` so it is not bundled and
 * not part of the app's runtime dependency graph.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  filterLiteLLMCatalog,
  LITELLM_MODELS_URL,
  type ModelCatalog,
} from "../src/ai/model-catalog-filter.ts";

const SEED_PATH = fileURLToPath(
  new URL("../src/ai/model-registry.seed.generated.ts", import.meta.url),
);

function renderSeedModule(catalog: ModelCatalog): string {
  const json = JSON.stringify(catalog, null, 2);
  return `/**
 * GENERATED by \`npm run gen:models\` — DO NOT EDIT BY HAND.
 *
 * A snapshot of the LiteLLM-filtered chat-model catalog (14-10). This is the
 * BUNDLED seed: the offline / first-run fallback the picker renders before any
 * user-instigated refresh. The on-device runtime cache overrides it once the
 * user taps "Refresh models" in AI settings. Regenerate whenever the frontier set
 * drifts; the runtime refresh keeps a live device current between regenerations.
 *
 * Source: ${catalog.source}
 * Snapshot generatedAt: ${catalog.generatedAt}
 */
import type { ModelCatalog } from "./model-catalog-filter";

export const MODEL_CATALOG_SEED: ModelCatalog = ${json} as const;
`;
}

async function main(): Promise<void> {
  process.stdout.write(`Fetching ${LITELLM_MODELS_URL}\n`);
  const res = await fetch(LITELLM_MODELS_URL);
  if (!res.ok) {
    throw new Error(`gen:models: fetch failed with HTTP ${res.status}`);
  }
  const raw: unknown = await res.json();
  const catalog = filterLiteLLMCatalog(raw, new Date());

  const counts = Object.entries(catalog.models)
    .map(([p, ids]) => `${p}=${ids.length}`)
    .join(" ");
  process.stdout.write(`Filtered catalog: ${counts}\n`);

  for (const [provider, ids] of Object.entries(catalog.models)) {
    if (ids.length === 0) {
      throw new Error(
        `gen:models: refusing to write an empty ${provider} list — the LiteLLM shape may have changed`,
      );
    }
  }

  writeFileSync(SEED_PATH, renderSeedModule(catalog), "utf8");
  process.stdout.write(`Wrote ${SEED_PATH}\n`);
}

main().catch((err) => {
  process.stderr.write(`${String(err)}\n`);
  process.exit(1);
});
